SmartShop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views import Login, Signup, Index, Cart, CheckOut, Orders
from .middlewares.auth import  auth_middleware

app_name = 'store'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('cart/', auth_middleware(Cart.as_view()), name='cart'),
    path('logout/', views.Logout, name='logout'),
    path('check-out', CheckOut.as_view(), name='checkout'),
    path('orders/', auth_middleware(Orders.as_view()), name='orders'),
    
]

store/models.py
from django.db import models
import datetime
# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    password = models.CharField(max_length=500)

    def __str__(self):
        return self.first_name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name



class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(max_length=200, null=True, blank=True)
    # image = models.ImageField(upload_to='uploads/products/')
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class OrderPlaced(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)                                             
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    delivered = models.BooleanField(default=False)

    def __str__(self):
        return str(self.product)

store/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .models import *
from django.contrib.auth.hashers import make_password, check_password
from django.views import View


# Create your views here.
class Index(View):

    def post(self, request):
        product_id = request.POST.get('product_id')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product_id)
            if quantity:
                if remove:
                    if quantity == 1:
                        cart.pop(product_id)
                    else:
                        cart[product_id] = quantity - 1
                else:
                    cart[product_id] = quantity + 1
            else:
                cart[product_id] = 1
        else:
            cart = {}
            cart[product_id] = 1
        request.session['cart'] = cart
        print(request.session['cart'])
        return redirect('store:index')
         



    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}


        products = None
        
        categories = Category.objects.all()
        cat_id = request.GET.get('category')
        if cat_id:
            products = Product.objects.filter(category=cat_id)
        else:
            products = Product.objects.all()

        context={'products':products, 'categories':categories}
        print('you are:', request.session.get('customer'))
        return render(request, 'store/index.html',context)




class Cart(View):
    def get(self, request):
        list_of_products_id_in_cart = list(request.session.get('cart').keys())
        products_in_cart = Product.objects.filter(id__in =list_of_products_id_in_cart)
        # print(products_in_cart)
        context = {'cart_products': products_in_cart}
        return render(request, 'store/cart.html',context)




class CheckOut(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer = request.session.get('customer')
        cart = request.session.get('cart')
        list_of_products = list(cart.keys())
        products = Product.objects.filter(id__in =list_of_products)
        print(address, phone, customer,cart, products)

        for product in products:
            order = OrderPlaced(customer=Customer.objects.get(id=customer),
                          product=product,
                          price=product.price,
                          address=address,
                          phone=phone,
                          quantity=cart.get(str(product.id)))
            order.save()
        request.session['cart'] = {}

        return redirect('store:cart')




class Orders(View):
    def get(self, request):
        customer_id = request.session.get('customer')
        customer = Customer.objects.get(id = customer_id)
        orders = OrderPlaced.objects.filter(customer=customer).order_by('-date')
        # print(orders)
        context = {'orders':orders}
        return render(request, 'store/orders.html',context)




class Signup(View):
    def get(self, request):
        return render(request, 'store/signup.html')
    def post(self, request):
        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        password = request.POST.get('password')

        # validation---
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }

        customer = Customer(first_name=first_name,
                                last_name=last_name,
                                phone=phone,
                                email=email,
                                password=password)

        error_message = self.validateCustomer(customer)
        emailExist = Customer.objects.filter(email=email)
         # email verification---
        if emailExist:
            error_message = 'Email already exist'

        if not error_message:
            customer.password = make_password(customer.password)
            customer.save()
            return redirect('store:login')
        else:
            context = {
                'error': error_message,
                'values': value,
            }
            return render(request, 'store/signup.html', context)

    def validateCustomer(self, customer):
        error_message = None
        
        if (not customer.first_name):
            error_message = "First Name Required !!"
        elif len(customer.first_name) < 3:
            error_message = 'First Name must be 4 char long or more'
        elif not customer.last_name:
            error_message = 'Last Name Required'
        elif len(customer.last_name) < 3:
            error_message = 'Last Name must be 4 char long or more'
        elif not customer.phone:
            error_message = 'Phone Number required'
        elif len(customer.phone) < 10:
            error_message = 'Phone Number must be 10 char Long'
        elif len(customer.password) < 6:
            error_message = 'Password must be 6 char long'
        elif len(customer.email) < 5:
            error_message = 'Email must be 5 char long'
       

        return error_message




class Login(View):
    return_url = None
    def get(self, request):
        Login.return_url = request.GET.get('return_url')
        return render(request, 'store/login.html')

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        customer = Customer.objects.filter(email=email).first()
        
        
        error_message = None
        if customer:
            flag = check_password(password, customer.password)
            if flag:
                request.session['customer'] = customer.id
                request.session['customer_name'] = customer.first_name

                if Login.return_url:
                    return HttpResponseRedirect(Login.return_url)
                else:
                    Login.return_url = None
                    return redirect('store:index')
            else:
                error_message = 'Email or Password Invalid'
        else:
            error_message = 'Email or Password Invalid'
        return render(request, 'store/login.html', {'error':error_message})




def Logout(request):
    request.session.clear()
    return redirect('store:login')

store/templates/store/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <title>SMART SHOP</title>


</head>

<body>

  <!-- navbar -->
  <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'store:index' %}"><span id="logo"><img
          src="{% static 'store/images/logo.png' %}" alt=""></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <div class="dropdown mx-5">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categories
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a href="/" class="list-group-item list-group-item-action">All Products</a>
            {% for category in categories %}
            <a href="/?category={{category.id}}" class="list-group-item list-group-item-action">{{category.name}}</a>
            {% endfor %}
          </div>
        </div>


      </ul>

      <ul class="navbar-nav my-2 my-lg-0">
        {% if request.session.customer %}
        <li class="nav-item active">
          <span class="nav-link" id="welcome"> Welcome {{request.session.customer_name}} </span>
        </li>
        {% endif %}



        <li class="nav-item active">
          <a class="nav-link" href="/cart">Cart
            <span class="badge badge-info">{{request.session.cart.keys|length}}</span>
            <span class="sr-only">(current)</span></a>
        </li>
        {% if request.session.customer %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'store:orders' %}">Orders <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="/logout">Logout <span class="sr-only">(current)</span></a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:signup' %}">Signup <span class="sr-only">(current)</span></a>

        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:login' %}">Login <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}


        <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li> -->

      </ul>

    </div>
  </nav>

  <!-- end of navbar -->

  <!-- body -->
  <div id="contain">
    {% block content %}

    {% endblock %}
  </div>
  <hr>

  <!-- footer starts -->

  <!-- Site footer -->
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>About</h6>
          <p class="text-justify">azimify.com <i>BE A GOOD BELIEVER </i> is an initiative to help the upcoming
            programmers with the code. Azimify focuses on providing the most efficient code or snippets as the code
            wants to be simple. We will help programmers build up concepts in different programming languages that
            include Python, PHP, HTML, CSS, Bootstrap, Django, JavaScript and Algorithm.</p>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Categories</h6>
          <ul class="footer-links">
            <li>{% for category in categories %}
              <a href="/?category={{category.id}}">{{category.name}}</a>
              <br>
              {% endfor %}</li>

          </ul>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Quick Links</h6>
          <ul class="footer-links">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Contribute</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Sitemap</a></li>
          </ul>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2020 Made with ❤️ by
            <a href="#">Shakir Azim</a>.
          </p>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- end footer -->


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</body>

</html>





<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}

{% block content %}
{% load cart %}
<div class="container">
  <div class="border rounded p-4 m-4">
    <p class="display-4 pl-4 ml-40">Your Cart</p>
    <div class="table-responsive-sm">
      <table class="table">
        <thead>
          <tr>
            <th>Sno.</th>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for product in cart_products %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td><img style="height: 80px;" class="" src="{{product.image.url}}" alt=""></td>
            <td>{{product.name}}</td>
            <td>{{product.price|currency}}</td>
            <td>{{product|cart_quantity:request.session.cart}}</td>
            <td>{{product|price_total:request.session.cart|currency}}</td>
          </tr>
          {% endfor %}

        <tfoot>
          <tr>
            <th colspan="3"></th>
            <th class="" colspan=""> Total </th>
            <th>{{cart_products|total_cart_price:request.session.cart|currency}}</th>
          </tr>
        </tfoot>
        </tbody>
      </table>

    </div>

    <hr>
    <div class="m-3 p-3">
      <a href="#" data-toggle="modal" data-target="#exampleModal"
        class="btn btn-outline-info border rounded  col-lg-3 float-right">Check Out</a>
    </div>


  </div>
</div>

<!-- Model templates using bootstrap-->




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Check Out Form
        </h5>
        <hr>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="m-2 p-3">
          <form action="/check-out" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="">Address</label>
              <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">

            </div>
            <div class="form-group">
              <label for="">Phone</label>
              <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
            </div>

            <input type="submit" class="btn float-right btn-outline-info col-lg-6" value="Check out">
          </form>
        </div>
      </div>

    </div>
  </div>
</div>



{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}

{% block content %}
{% load cart %}

<div class="container-fluid mt-1">

    <div class="row" id="banner">
        <div id="banner-text" class="col-lg-6">
            <h1>Demo Website</h1>
            <p> <span id="e-commerce-text"> E-Commerce </span> Using Python (Django) </p>
        </div>
        
        

    </div>



    <h1 style="text-align: center;">Collections</h1>

    <div class="row">
        <!-- all products here -->
        <div id="products" class="col-lg-12 mx-auto">
            <div class="row mx-auto">
                {% for product in products %}
                <div class="card mx-auto mb-3" id="product{{forloop.counter}}" style="width: 18rem;">
                    <img src="{{product.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-title">{{product.name}}</p>
                        <p class="card-text"><b>{{product.price|currency}}</b></p>
                        <!-- {{ product | is_in_cart:request.session.cart }} -->


                    </div>

                    <div class="card-footer p-0 no-gutters">
                        {% if product|is_in_cart:request.session.cart %}
                        <div class="row no-gutters">

                            <form action="/#product{{forloop.counter}}" method="post" class="col-2">
                                {% csrf_token %}
                                <input hidden type="text" name="product_id" value="{{product.id}}">
                                <input hidden type="text" name="remove" value="True">
                                <input class="btn-btn-block btn-secondary" type="submit" value=" - ">
                            </form>
                            <div class="text-center col"> {{product|cart_quantity:request.session.cart}} in Cart </div>
                            <form action="/#product{{forloop.counter}}" method="post" class="col-2">
                                {% csrf_token %}
                                <input hidden type="text" name="product_id" value="{{product.id}}">
                                <input class="btn-btn-block btn-secondary" type="submit" value=" + ">
                            </form>
                        </div>
                        {% else %}


                        <form action="/#product{{forloop.counter}}" method="post" class="btn-block">
                            {% csrf_token %}
                            <input hidden type="text" name="product_id" value="{{product.id}}">
                            <input type="submit" class="float-right btn btn-light  form-control" value="Add To Cart">
                        </form>
                        {% endif %}


                    </div>


                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

store/templates/store/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background:#400a0a !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background:#694e14;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8), 0 6px 20px 0 rgba(0, 0, 0, 0.7);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.7), 0 6px 20px 0 rgba(0, 0, 0, 0.7);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.7), 0 6px 20px 0 rgba(0, 0, 0, 0.7);
			border-radius: 50px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Login</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form  method="POST" action="">
						{% csrf_token %}

						{% if error %}
						<div class="alert alert-danger" role="alert">
						  {{error}}
						</div>
						{% endif %}

						

						

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="email" name="email" value="{{values.email}}">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password">
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Login">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Register New Account? <a href="{% url 'store:signup' %}" class="ml-2">Register</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		
		form_fields[1].placeholder='Email';
		form_fields[2].placeholder='Password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

store/templates/store/orders.html
{% extends 'store/base.html' %}

{% block content %}
{% load cart %}
<div class="container">
    <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-40">Your Orders</p>
        <div class="table-responsive-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Sno.</th>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Date</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><img style="height: 80px;" class="" src="{{order.product.image.url}}" alt=""></td>
                        <td>{{order.product.name}}</td>
                        <td>{{order.date}}</td>
                        <td>{{order.price|currency}}</td>
                        <td>{{order.quantity}}</td>
                        <td>{{order.quantity|multiply:order.price}}</td>
                        {% if order.delivered%}
                        <td><small class="badge badge-success">Delivered</small></td>
                        {% else %}
                        <td><small class="badge badge-warning">Pending</small></td>
                        {% endif %}
                    </tr>
                    {% endfor %}


                </tbody>
            </table>

        </div>

    </div>
</div>

{% endblock %}